#!/usr/bin/env bash
# Bash script that will display information about subdomains.

get_subdomain_info() {

  domain=$1
  subdomain=$2

  if [ -z "$subdomain" ]; then
    subdomains=("www" "lb-01" "web-01" "web-02")
  else
    subdomains=("$subdomain")
  fi

  for sub in "${subdomains[@]}"; do
    output=$(dig +short "$sub.$domain")
    record_type=$(dig "$sub.$domain" | awk '$3 == "IN" { print $4 }')
    echo "The subdomain $sub is a $record_type record and points to $output"
  done
}

get_subdomain_info "$1" "$2"

