#!/usr/bin/env bash
# transfers a file from our client to a server:
# Format:
#   scp "PATH_TO_FILE" -i "" stricthostkeychecking=no "username@ip"

if [ $# -lt 3 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp "$1" -i "$4" stricthostkeychecking=no "$3@$2":~/
fi
