#!/usr/bin/env bash
# Install nginx on my web01 server
# Configure nginx server so /redirect_me is redirecting to another page
# Redirection must be a 301 moved permanently

# Update package and install Nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# Configure Nginx to listen on port 80
sudo sed -i 's/listen\s*80;/listen 80 default_server;/g' /etc/nginx/sites-available/default

# Create a new index.html in /var/www/html directory file with "Hello World!" in it
echo "Hello World!" > /var/www/html/index.html

# setting up the redirect
echo "server {
	listen 80 default_server;
	listen [::]:80 default_server;

	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}
	location / {
		root /var/www/html;
		index index.html;
	}
}" | sudo tee /etc/nginx/sites-available/default > /dev/null

sudo service nginx restart
