#!/usr/bin/env bash
# Install nginx on my web01 server
# Configure nginx server so /redirect_me is redirecting to another page
# Redirection must be a 301 moved permanently

# Update package and install Nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# Configure Nginx to listen on port 80
sudo sed -i 's/listen\s*80;/listen 80 default_server;/g' /etc/nginx/sites-available/default

# Create a custom index.html file with "Hello World!"
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

# Create a custom 404.html error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null

# Set up the redirect, add custom header
sudo tee /etc/nginx/sites-available/default > /dev/null <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;
    root /var/www/html;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    error_page 404 /404.html;
    location = /404.html {
        internal;
    }

    # Add custom header
    add_header X-Served-By \$hostname;
}
EOF

# Enable the new configuration by creating a symbolic link
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/

# Test the configuration and restart Nginx
sudo nginx -t && sudo service nginx restart
