#!/usr/bin/env bash
# Installing and Configuring HAproxy loadbalancer on lb-01 server

# Install HAproxy
sudo apt-get -y update
sudo apt-get -y install haproxy

# Enable HAproxy init script
sudo sed -i 's/ENABLED=.*/ENABLED=1/' /etc/default/haproxy

# Configure HAproxy with web servers
echo "
frontend http-in
  bind *:80
  default_backend webservers

backend webservers
  balance roundrobin
  server 118476-web-01 54.197.21.216:80 check
  server 118476-web-02 100.25.138.59:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null

# Start the HAproxy load balancer service
sudo service haproxy enable
sudo service haproxy start
