#!/usr/bin/env bash
# Bash script that displays listening ports:
#     That only shows listening sockets
#     That shows the PID and name of the program to which each socket belongs
# -l : That only shows listening sockets
# -p : That shows the PID and name of the program to which each socket belongs

netstat -lp
