#!/usr/bin/env bash
# Script that checks why my ubuntu container isn't connecting on port 80
sudo sed -i 's/8080 default_server/80 default_server/g' /etc/nginx/sites_enabled/default
sudo service restart
