#!/usr/bin/env bash
# Script that checks why my ubuntu container isn't connecting on port 80
# take the nginx config and give it a new link and restart the server
sudo ln -fs /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
