#!/usr/bin/env bash
# script that:
# creates file /var/run/holbertonscript.pid containing its PID.
# displays "To infinity and beyond" indefinitely.
# displays "I hate the kill command" on SIGTERM signal.
# displays "Y U no love me?!" on SIGINT signal.
# deletes the pid file and terminates on SIGQUIT or SIGTERM signal.
touch /var/run/myscript.pid
echo "$$" >> /var/run/myscript.pid

trap "echo I hate the kill command; exit" SIGTERM
trap "echo I hate the kill command" SIGINT
trap "exit" SIGQUIT

while true; do
    echo "To infinity and beyond"
    sleep 2
done
