#!/usr/bin/env bash
# script that displays the content of the file /etc/passwd:
# it only displays:
# username
# user id
# Home directory path for the user
file=/etc/passwd
while read -r line;
do
    echo "$line" | cut -d':' -f1,3,6
done <"$file"
