#!/usr/bin/env bash
# script that displays Best School 10 times, but for the 9th iteration
# ,displays Best School and then Hi on a new line
count=10
i=1
while (( i<=count )); do
    if (( i != 9 ))
    then
        echo Best School
    else
        echo Hi
    fi
    i=$((i+1))
done
