#!/usr/bin/env bash
# loops from 1 through 10
count=10
i=1
while (( i<=count )); do
    if (( i==4 ))
    then
        echo bad luck
    elif (( i==8 ))
    then
        echo good luck
    else
        echo Best School
    fi

    i=$((i+1))
done
