#!/usr/bin/env bash
# displays numbers 1-20;
count=20
i=1
while (( i<=count)); do
    case $i in
    4)  echo "$i"
        echo "bad luck from China";;
    9)  echo "$i"
        echo "bad luck from Japan";;
    17) echo "$i"
        echo "bad luck from Italy";;
    *)  echo "$i"
    esac

    i=$((i+1))
done
