#!/usr/bin/env bash
# script that displays the time for 12 hours and 59 minutes:
hours=12
minutes=59
i=0
j=1
while (( i<=hours )); do 
    echo "Hour: $i"
    while (( j<=minutes )); do
	echo "$j"
	j=$((j+1))
    done
    j=1
    i=$((i+1))
done
