#!/usr/bin/env bash
# Bash script that configures an Ubuntu server with the below requirements.
# Requirements:
#     localhost resolves to 127.0.0.2
#     facebook.com resolves to 8.8.8.8.

hostsfile=~/hosts.new
cp /etc/hosts $hostsfile

echo "127.0.0.2		localhost" > $hostsfile
echo "8.8.8.8		facebook.com" >> $hostsfile

cp -f $hostsfile /etc/hosts
