#!/usr/bin/env bash

# Set the name of the private key
private_key="school"

# Set the number of bits in the key
key_bits="4096"

# Set the passphrase for the key
key_passphrase="betty"

# Generate the key pair
ssh-keygen -t rsa -b "$key_bits" -f "$private_key" -N "$key_passphrase"
